text1 = "xmenjxmefagfgudemvdseusxvjzgjwsmefdugadxtsemefdugdzmckdzfenxgfefgmvdsesupjzgemuptuklfccfmxtmscenszgedu"
text2 = "gezjukemjumpjupztejgjchwstigfmajdsefzmaetajazjmejmxjemfndzytgsmctxmkjdzujxdutaxmbjaduvjaetdvgymzqqdszfzmaetajfzdvcjxg"

# fzmaetaj = PRACTICE
# mvdse = ABOUT
text1 = text1.replace('f', 'P')
text1 = text1.replace('z', 'R')
text1 = text1.replace('m', 'A')
text1 = text1.replace('a', 'C')
text1 = text1.replace('e', 'T')
text1 = text1.replace('t', 'I')
text1 = text1.replace('j', 'E')
text1 = text1.replace('p', 'D')
text1 = text1.replace('v', 'B')
text1 = text1.replace('d', 'O')
text1 = text1.replace('s', 'U')
text1 = text1.replace('c', 'L')
text1 = text1.replace('x', 'M')
text1 = text1.replace('g', 'S')
text1 = text1.replace('n', 'H')
text1 = text1.replace('y', 'V')
text1 = text1.replace('u', 'N')
text1 = text1.replace('k', 'G')
text1 = text1.replace('b', 'K')
text1 = text1.replace('w', 'Q')
text1 = text1.replace('l', 'W')
print(text1)

text2 = text2.replace('f', 'P')
text2 = text2.replace('z', 'R')
text2 = text2.replace('m', 'A')
text2 = text2.replace('a', 'C')
text2 = text2.replace('e', 'T')
text2 = text2.replace('t', 'I')
text2 = text2.replace('j', 'E')
text2 = text2.replace('p', 'D')
text2 = text2.replace('v', 'B')
text2 = text2.replace('d', 'O')
text2 = text2.replace('s', 'U')
text2 = text2.replace('c', 'L')
text2 = text2.replace('x', 'M')
text2 = text2.replace('g', 'S')
text2 = text2.replace('n', 'H')
text2 = text2.replace('y', 'V')
text2 = text2.replace('u', 'N')
text2 = text2.replace('k', 'G')
text2 = text2.replace('b', 'K')
text2 = text2.replace('w', 'Q')
text2 = text2.replace('l', 'W')
print(text2)

